# This image adds the authorization schema and sample OAuth 2.0 credentials to a PostgreSQL database.

FROM postgres:latest
MAINTAINER Bell Eapen <github_public@gulfdoctor.net>

COPY init.sql /docker-entrypoint-initdb.d/